/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GeneratePerson;

/**
 *
 * @author plizak
 */
public class GeneratorOsob extends javax.swing.JFrame {

    /**
     * Creates new form GeneratorOsob
     */
    public GeneratorOsob() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbPan = new javax.swing.JRadioButton();
        rbPani = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        chbInz = new javax.swing.JCheckBox();
        chbProf = new javax.swing.JCheckBox();
        chbMgr = new javax.swing.JCheckBox();
        chbDr = new javax.swing.JCheckBox();
        chbLic = new javax.swing.JCheckBox();
        chbHab = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lImiona = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        tfNazwisko = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lDzien = new javax.swing.JLabel();
        lMiesiac = new javax.swing.JLabel();
        lRok = new javax.swing.JLabel();
        cbMiesiac = new javax.swing.JComboBox<>();
        sRok = new javax.swing.JSpinner();
        ffDzien = new javax.swing.JFormattedTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        bWypisz = new javax.swing.JButton();
        bZeruj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 3));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Plec", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        bgButtonGroup.add(rbPan);
        rbPan.setSelected(true);
        rbPan.setText("Pan");
        rbPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPanActionPerformed(evt);
            }
        });
        jPanel1.add(rbPan);

        bgButtonGroup.add(rbPani);
        rbPani.setText("Pani");
        jPanel1.add(rbPani);

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tytul", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(3, 2));

        chbInz.setText("inz.");
        chbInz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbInzActionPerformed(evt);
            }
        });
        jPanel2.add(chbInz);

        chbProf.setText("Prof.");
        chbProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbProfActionPerformed(evt);
            }
        });
        jPanel2.add(chbProf);

        chbMgr.setText("mgr");
        jPanel2.add(chbMgr);

        chbDr.setText("dr");
        jPanel2.add(chbDr);

        chbLic.setText("lic");
        jPanel2.add(chbLic);

        chbHab.setText("hab.");
        jPanel2.add(chbHab);

        getContentPane().add(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Imie", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        lImiona.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Piotr", "Mateusz", "Jacek", "Michal‚", "Danuta", "Anna", "Cecylia", "Karolina", "Maria" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lImiona.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lImiona.setSelectedIndex(0);
        jScrollPane1.setViewportView(lImiona);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nazwisko", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());

        tfNazwisko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNazwiskoActionPerformed(evt);
            }
        });
        jPanel4.add(tfNazwisko, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data urodz.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 0, 51))); // NOI18N

        lDzien.setText("Dzien");

        lMiesiac.setText("Miesiac");

        lRok.setText("Rok");

        cbMiesiac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Styczen", "Luty", "Marzec", "Kwiecien", "Maj", "Czerwiec", "Lipiec", "Sierpien", "Wrzesien", "Pazdziernik", "Listopad", "Grudzien" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lMiesiac)
                    .addComponent(lRok)
                    .addComponent(lDzien))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sRok)
                    .addComponent(cbMiesiac, 0, 174, Short.MAX_VALUE)
                    .addComponent(ffDzien)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDzien)
                    .addComponent(ffDzien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMiesiac)
                    .addComponent(cbMiesiac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lRok)
                    .addComponent(sRok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 0, 51))); // NOI18N
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setMaximumSize(new java.awt.Dimension(3276, 3276));
        jPanel7.setLayout(new java.awt.GridLayout());

        bWypisz.setText("Wypisz");
        bWypisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bWypiszActionPerformed(evt);
            }
        });
        jPanel7.add(bWypisz);

        bZeruj.setText("Zeruj");
        bZeruj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bZerujActionPerformed(evt);
            }
        });
        jPanel7.add(bZeruj);

        jPanel6.add(jPanel7, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel6);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bWypiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bWypiszActionPerformed
        String opis = "";
        
        if (rbPan.isSelected())
        {
            opis += "Pan";
        }
        else
        {
            opis += "Pani";
        }
        
        if(chbInz.isSelected())
        {
            opis += " Inz";
        }
        
        if(chbLic.isSelected())
        {
            opis += " Lic";
        }
        
        if(chbMgr.isSelected())
        {
            opis += " Mgr";
        }
        
        if(chbDr.isSelected())
        {
            opis += " Dr";
        }
        
        if(chbHab.isSelected())
        {
            opis += " Hab";
        }
        
        if(chbProf.isSelected())
        {
            opis += " Prof";
        }
        
        opis += " " + lImiona.getSelectedValue();
        
        opis += " " +tfNazwisko.getText();
        
        System.out.println("Osoba: " + opis);
    }//GEN-LAST:event_bWypiszActionPerformed

    private void chbInzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbInzActionPerformed
        
    }//GEN-LAST:event_chbInzActionPerformed

    private void chbProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbProfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbProfActionPerformed

    private void bZerujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bZerujActionPerformed
        rbPan.setSelected(false);
        rbPani.setSelected(false);
        
        chbProf.setSelected(false);
        chbHab.setSelected(false);
        chbDr.setSelected(false);
        chbMgr.setSelected(false);
        chbLic.setSelected(false);
        chbInz.setSelected(false);
        
        //lImiona.setSelectedIndex(0);
        lImiona.clearSelection();
    }//GEN-LAST:event_bZerujActionPerformed

    private void tfNazwiskoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNazwiskoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNazwiskoActionPerformed

    private void rbPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPanActionPerformed
        
    }//GEN-LAST:event_rbPanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeneratorOsob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeneratorOsob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeneratorOsob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeneratorOsob.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeneratorOsob().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bWypisz;
    private javax.swing.JButton bZeruj;
    private javax.swing.ButtonGroup bgButtonGroup;
    private javax.swing.JComboBox<String> cbMiesiac;
    private javax.swing.JCheckBox chbDr;
    private javax.swing.JCheckBox chbHab;
    private javax.swing.JCheckBox chbInz;
    private javax.swing.JCheckBox chbLic;
    private javax.swing.JCheckBox chbMgr;
    private javax.swing.JCheckBox chbProf;
    private javax.swing.JFormattedTextField ffDzien;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lDzien;
    private javax.swing.JList<String> lImiona;
    private javax.swing.JLabel lMiesiac;
    private javax.swing.JLabel lRok;
    private javax.swing.JRadioButton rbPan;
    private javax.swing.JRadioButton rbPani;
    private javax.swing.JSpinner sRok;
    private javax.swing.JTextField tfNazwisko;
    // End of variables declaration//GEN-END:variables
}
